sudo: required

language: c

os:
  - linux

services:
  - docker

cache:
  directories:
    - $HOME/build

env:
  - TAG=latest SUFFIX=""

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: 
    - taiji-Linux-x86_64$SUFFIX
  on:
    tags: true

script:
  - docker pull kaizhang/centos-haskell-stack:$TAG
  - docker run
    -v $HOME/build:/root/.stack
    -v `pwd`:/source:rw
    kaizhang/centos-haskell-stack:$TAG
    /bin/bash -c
    "cd source &&
    stack install --stack-yaml stack$SUFFIX.yaml --allow-different-user &&
    mv /root/.local/bin/taiji /source/taiji-Linux-x86_64$SUFFIX"

stages:
  - build dependencies 1
  - test

jobs:
  include:
    - stage: build dependencies
      script:
        - docker pull kaizhang/centos-haskell-stack:$TAG
        - docker run
          -v $HOME/build:/root/.stack
          -v `pwd`:/source:rw
          kaizhang/centos-haskell-stack:$TAG
          /bin/bash -c
          "cd source &&
          stack build --only-dependencies --stack-yaml stack$SUFFIX.yaml --allow-different-user"
      env:
        - TAG=latest SUFFIX=""