resolver:    lts-10.3

packages:
- '.'

extra-deps:

- git:     https://github.com/kaizhang/SciFlow.git
  commit:  997ea40bff1552248052fd82611094dd06dec217

- git:     https://github.com/Taiji-pipeline/Taiji-types.git
  commit:  61f13cc6f4d63b9ce3712710dcdd716c19aba487

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  6af63147064c8bb7721e719fa6accc4aecea67bd

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  8c092b0fbc69ccdd387c0272a1fcb91aceaafc25

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  ca206d5d59398d22be695128d30532aa92cdb330

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  1b073529a9c98afdebc1d0f35b24b8690b2d4c88

- bioinformatics-toolkit-0.3.2
- HsHTSLib-1.3.2.2
- drmaa-0.2.0
- haskell-igraph-0.3.0
- clustering-0.3.1
