resolver:    lts-12.24

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-types.git
  commit:  95aad5f7f30e74ca330167c256daf003c1ee60ad

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  607bbb44785320d4d0963ed0fc4793f262c0942c

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  19edc88b4bbc7a9ff29ed5bca5d0acf6e2e864b9

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  25d47aad0cd5903e4acfddec804d9c04366f4581

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  63b07c26067e3bb0610051cc61d369807bedde60

- git:     https://github.com/Taiji-pipeline/Taiji-ChIP-seq.git
  commit:  ad5cd2364c4f434e270b86ce004153ec17106d21

- git:     https://github.com/kaizhang/bioinformatics-toolkit.git
  commit:  4d54eab41f76f6fd5a0ffbea9fd52e0b8b6ee829
  subdirs:
    - bioinformatics-toolkit

- HsHTSLib-1.3.2.3
- drmaa-0.2.0
- clustering-0.4.0
- SciFlow-0.6.2
- haskell-igraph-0.7.1