resolver:    lts-10.10

packages:
- '.'

extra-deps:

- git:     https://github.com/kaizhang/SciFlow.git
  commit:  997ea40bff1552248052fd82611094dd06dec217

- git:     https://github.com/Taiji-pipeline/Taiji-types.git
  commit:  558901d26f44bdbffd217b9a73bdbbab56493c62

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  6af63147064c8bb7721e719fa6accc4aecea67bd

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  12d25db4045eccb84b2a8b790db7eec4982e4365

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  a303a6a96f1db448579924b991d795fb4b9909e1

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  616bc4220b7462f09fc9ba5ba28e160845c7f5b9

- bioinformatics-toolkit-0.4.0
- HsHTSLib-1.3.2.2
- drmaa-0.2.0
- haskell-igraph-0.3.0
- clustering-0.3.1
