resolver: nightly-2017-08-20

packages:
- '.'
- '../Taiji-types'

- location:
    git: https://github.com/Taiji-pipeline/bio-pipelines.git
    commit: 1989e84be6b55d64543ae91a79da82c309058ad1

- location:
    git: https://github.com/Taiji-pipeline/bio-experiments.git
    commit: 821fa7d109fb535a7eea389a49c45e51b3b37242

- location:
    git: https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
    commit: 60067633fe9b83580acae14e8bd2ddf2e04ca6d1

- location:
    git: https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
    commit: ade0f99f2191ff39a9a1ef5dd62fddaff8d8dead

- location:
    git: https://github.com/kaizhang/SciFlow.git
    commit: 997ea40bff1552248052fd82611094dd06dec217

extra-deps:
- bioinformatics-toolkit-0.3.2
- HsHTSLib-1.3.2.2
- cereal-vector-0.2.0.1
- drmaa-0.2.0
- haskell-igraph-0.3.0
