resolver: nightly-2017-10-11

packages:
- '.'

- location:
    git: https://github.com/kaizhang/SciFlow.git
    commit: 997ea40bff1552248052fd82611094dd06dec217

- location:
    git: https://github.com/Taiji-pipeline/Taiji-types.git
    commit: 61f13cc6f4d63b9ce3712710dcdd716c19aba487

- location:
    git: https://github.com/Taiji-pipeline/bio-pipelines.git
    commit: db08736dc7be1f97ce1f0eefe28a92320b393c91

- location:
    git: https://github.com/Taiji-pipeline/bio-experiments.git
    commit: 8c092b0fbc69ccdd387c0272a1fcb91aceaafc25

- location:
    git: https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
    commit: 3a2119c42bcf54d5a0ddbb03b032e24d642c3a8b

- location:
    git: https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
    commit: 02e8c312533d27b2ca1d18026c9137cf9d9226b9

extra-deps:
- bioinformatics-toolkit-0.3.2
- HsHTSLib-1.3.2.2
- drmaa-0.2.0
- haskell-igraph-0.3.0
