resolver: nightly-2019-03-14

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-types.git
  commit:  9466d7f69977778f50bfdd60fd4fbf62a93dea7b

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  bd10c445832a3f3bdf82b57ddf1224397b78390b

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  3157224ccebae6b3ce26185a85b8093494878ed4

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  94c3de1a5e13e048d7cc5d53cc0295ca395ac1e7

- git:     https://github.com/Taiji-pipeline/Taiji-scRNA-seq.git
  commit:  a39362a0fa6a27df4787e9e7d6aa942115f1eec7

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  41e4e96b0f6f18737e1ff6d03d007c7cea4f1a6a

- git:     https://github.com/Taiji-pipeline/Taiji-ChIP-seq.git
  commit:  ad5cd2364c4f434e270b86ce004153ec17106d21

- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  e9db8aad4ca005257a464a5eff0e5ff15aa761b2

- git:     https://github.com/kaizhang/bioinformatics-toolkit.git
  commit:  d1ce0f73c04c77edd674cad92904789f5fd46409
  subdirs: 
    - bioinformatics-toolkit

- HsHTSLib-1.9.2
- drmaa-0.2.0
- clustering-0.4.1
- SciFlow-0.6.2