resolver: nightly-2019-04-05

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-types.git
  commit:  d9398a3db84607a4d905afb52cee7cab88c722c2

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  4e8dfffd751229259e6e3cede1483fb7fe7bf018

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  4c425bf96f392fb1f9098821f643895ef1226151

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  94c3de1a5e13e048d7cc5d53cc0295ca395ac1e7

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  b7578e93086e0b92a1561c06dbc78fd281f00678

- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  e9db8aad4ca005257a464a5eff0e5ff15aa761b2

- git:     https://github.com/Taiji-pipeline/Taiji-scRNA-seq.git
  commit:  95c940d253f67028de6fd8e65a01c674e43d81e4

- git:     https://github.com/Taiji-pipeline/Taiji-scATAC-seq.git
  commit:  b822bca54bda96082268ff33ba6a4c577df3fb96

- bioinformatics-toolkit-0.7.0
- HsHTSLib-1.9.2
- drmaa-0.2.0
- clustering-0.4.1
- SciFlow-0.6.2