resolver: nightly-2017-10-11

packages:
- '.'

- location:
    git: https://github.com/kaizhang/SciFlow.git
    commit: 997ea40bff1552248052fd82611094dd06dec217

- location:
    git: https://github.com/Taiji-pipeline/Taiji-types.git
    commit: 61f13cc6f4d63b9ce3712710dcdd716c19aba487

- location:
    git: https://github.com/Taiji-pipeline/bio-pipelines.git
    commit: 2c2043d5b88a36ead5102f9139564a89cb8b130f

- location:
    git: https://github.com/Taiji-pipeline/bio-experiments.git
    commit: 64256700716dc2f492f63629afb642e6d716047a

- location:
    git: https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
    commit: de36468d7fe69d88bf546cd88c2a2b24e1728723

- location:
    git: https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
    commit: 1e32552469632209a2d652b3b1127c281efc943a

extra-deps:
- bioinformatics-toolkit-0.3.2
- HsHTSLib-1.3.2.2
- drmaa-0.2.0
- haskell-igraph-0.3.0
