resolver: nightly-2017-08-15

packages:
- '.'
- '../SciFlow'

- location:
    git: https://github.com/Taiji-pipeline/bio-pipelines.git
    commit: f6b87b77b7835d18078cf88d070851ccb08eaf62

- location:
    git: https://github.com/Taiji-pipeline/bio-experiments.git
    commit: 821fa7d109fb535a7eea389a49c45e51b3b37242

- location:
    git: https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
    commit: 60067633fe9b83580acae14e8bd2ddf2e04ca6d1

- location:
    git: https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
    commit: ade0f99f2191ff39a9a1ef5dd62fddaff8d8dead

extra-deps:
- bioinformatics-toolkit-0.3.2
- HsHTSLib-1.3.2.2
- cereal-vector-0.2.0.1
- rainbow-0.28.0.4
- lens-simple-0.1.0.9
- drmaa-0.2.0
- haskell-igraph-0.3.0
