resolver:    lts-11.2

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-types.git
  commit:  558901d26f44bdbffd217b9a73bdbbab56493c62

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  a8cd7f979766c4f2eefed45bde6ac695aec6b80c

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  8093bee3480265952b6fb1694bef3498d5182859

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  52ff3046e8033cb97c03a1174e19f2a36ebff9ef

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  c5e344dfaf285e927461ead818e21c16f18fecb5

- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  71eda45fa45ff2bd765ccb5538f55c330b8129b8

- bioinformatics-toolkit-0.5.0
- HsHTSLib-1.3.2.3
- drmaa-0.2.0
- clustering-0.4.0
- SciFlow-0.6.1

- graphviz-2999.19.0.0
- fgl-5.5.4.0
