resolver: nightly-2017-10-11

packages:
- '.'

- location:
    git: https://github.com/kaizhang/SciFlow.git
    commit: 997ea40bff1552248052fd82611094dd06dec217

- location:
    git: https://github.com/Taiji-pipeline/Taiji-types.git
    commit: 61f13cc6f4d63b9ce3712710dcdd716c19aba487

- location:
    git: https://github.com/Taiji-pipeline/bio-pipelines.git
    commit: f59caa9f7bffececff5576ec7980696c639f00f4

- location:
    git: https://github.com/Taiji-pipeline/bio-experiments.git
    commit: 65eb19f4aefb91dbbe18469b6ffffb6b12d00f55

- location:
    git: https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
    commit: e0403b85485a4bbd292965a50e5726b8a9952c33

- location:
    git: https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
    commit: 02e8c312533d27b2ca1d18026c9137cf9d9226b9

extra-deps:
- bioinformatics-toolkit-0.3.2
- HsHTSLib-1.3.2.2
- drmaa-0.2.0
- haskell-igraph-0.3.0
