resolver:    lts-11.3

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-types.git
  commit:  129a77c6ea8f1202ad2dbd824433565209e55559

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  a8cd7f979766c4f2eefed45bde6ac695aec6b80c

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  8093bee3480265952b6fb1694bef3498d5182859

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  43661a44a16ae42f9a0995c8737b00cade2a06f8

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  c5e344dfaf285e927461ead818e21c16f18fecb5

- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  74612b98831b2997019b1099a1c5130fd8cb106a

- bioinformatics-toolkit-0.5.0
- HsHTSLib-1.3.2.3
- drmaa-0.2.0
- clustering-0.4.0
- SciFlow-0.6.1

- graphviz-2999.19.0.0
- fgl-5.5.4.0
