resolver:    lts-10.7

packages:
- '.'

extra-deps:

- git:     https://github.com/kaizhang/SciFlow.git
  commit:  997ea40bff1552248052fd82611094dd06dec217

- git:     https://github.com/Taiji-pipeline/Taiji-types.git
  commit:  61f13cc6f4d63b9ce3712710dcdd716c19aba487

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  6af63147064c8bb7721e719fa6accc4aecea67bd

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  8c092b0fbc69ccdd387c0272a1fcb91aceaafc25

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  a303a6a96f1db448579924b991d795fb4b9909e1

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  e2734316312c10a1557c86f0c1dc3a6f06425895

- bioinformatics-toolkit-0.4.0
- HsHTSLib-1.3.2.2
- drmaa-0.2.0
- haskell-igraph-0.3.0
- clustering-0.3.1
