resolver:    nightly-2018-06-05

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-types.git
  commit:  fb8e5f5d98817531f5508cfc9f71a276f5d4fad0

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  9aa46fbad740dda0469a86e819e7f3640c0ab22a

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  8d9deaef85b0311d3fe58f3b4cf21efe5e5bf151

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  2a858817f26d7160da8d9b8c4a83f4b833d324c7

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  615af28de48b5959bdb7113a6f08d1397210c33e

- git:     https://github.com/Taiji-pipeline/Taiji-ChIP-seq.git
  commit:  ad5cd2364c4f434e270b86ce004153ec17106d21

- git:     https://github.com/kaizhang/bioinformatics-toolkit.git
  commit:  4d54eab41f76f6fd5a0ffbea9fd52e0b8b6ee829
  subdirs:
    - bioinformatics-toolkit

- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  1987cba3319db7749391dbc40131e56452e4c150

- HsHTSLib-1.3.2.3
- drmaa-0.2.0
- clustering-0.4.0
- SciFlow-0.6.2